# Generated by Django 4.2.4 on 2024-01-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagename", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="myapp/images/")),
            ],
        ),
    ]
